import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: {
    extend: {
      colors: {
        canvas: "#fafaf8",
        surface: "#ffffff",
        "surface-hover": "#f3f3f1",
        "surface-muted": "#f0f0ed",
        border: "#e5e5e0",
        "border-light": "#efefea",
        "image-frame": "#e8e8e4",
        accent: "#f04e23",
        "accent-light": "#fde8e3",
        "accent-hover": "#d43d16",
        "accent-dark": "#b8330e",
        "secondary-accent": "#e67700",
        "focus-ring": "#f04e23",
        rule: "#e5e5e0",
        "text-primary": "#1a1a18",
        "text-secondary": "#6b6b65",
        "text-muted": "#4a4a46",
        "text-inverted": "#ffffff",
        "text-link": "#f04e23",
        // Legacy aliases
        "canvas-black": "#fafaf8",
        "surface-slate": "#f0f0ed",
        "jelly-mint": "#f04e23",
        "verge-ultraviolet": "#e67700",
        "console-mint-border": "#d43d16",
        "deep-link-blue": "#f04e23",
        "focus-cyan": "#f04e23",
        "purple-rule": "#e5e5e0",
        "hazard-white": "#1a1a18",
        "primary-text": "#1a1a18",
        "secondary-text": "#6b6b65",
        "muted-text": "#4a4a46",
        "inverted-text": "#ffffff",
      },
      fontFamily: {
        hero: ['"Bebas Neue"', '"Noto Sans SC"', "Impact", "Arial Black", "sans-serif"],
        sans: ['"Space Grotesk"', '"Noto Sans SC"', "Helvetica", "Arial", "sans-serif"],
        mono: ['"JetBrains Mono"', "Courier New", "monospace"],
        serif: ['"Newsreader"', "Georgia", "Times New Roman", "serif"],
      },
      borderRadius: {
        input: "2px",
        image: "3px",
        nested: "4px",
        card: "20px",
        feature: "24px",
        promo: "30px",
        pill: "40px",
        round: "50%",
      },
      letterSpacing: {
        kicker: "0.1em",
        label: "0.08em",
        mono: "0.12em",
        tight: "-0.02em",
        hero: "-0.01em",
      },
      lineHeight: {
        hero: "1.05",
        display: "1.08",
        tight: "1.15",
        snug: "1.25",
        normal: "1.5",
        relaxed: "1.65",
        loose: "1.8",
      },
      spacing: {
        "4.5": "1.125rem",
      },
    },
  },
  plugins: [],
};
export default config;
